# Generated by Django 5.2.17 on 2026-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='assistido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filme',
            name='data_assistido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
