# Generated by Django 5.2.17 on 2026-09-02 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_filme_assistido_filme_data_assistido_filme_diretor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
