# Generated by Django 5.2.17 on 2026-09-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_alter_filme_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='bio',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='curso',
            new_name='pais_origem',
        ),
    ]
