# Generated by Django 5.2.17 on 2026-09-29 20:05

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0004_remove_filme_bio_remove_filme_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmePais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_origem', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='filme',
            name='pais_origem',
        ),
    ]
