# Generated by Django 5.2.17 on 2026-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_filmepais_remove_filme_pais_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeDiretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilmeGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
    ]
