# Generated by Django 5.2.17 on 2026-09-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0006_filmediretor_filmegenero_remove_filme_diretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmediretor',
            name='filme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados_diretor', to='filme.filme'),
        ),
        migrations.AddField(
            model_name='filmegenero',
            name='filme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados_genero', to='filme.filme'),
        ),
        migrations.AddField(
            model_name='filmepais',
            name='filme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados_pais', to='filme.filme'),
        ),
    ]
